### ISSUE TITLE
How to install L4T?

### ISSUE THREAD

**Issue by lovedheart** [lgeek/gnu-linux-on-acer-chromebook-13#4]
Hello, I am new to linux. Can u give instruction steps for installing L4T for chromebook tegra k1? Thank u.

**Comment by lgeek** [comment]
Hi, maybe [this](https://www.reddit.com/r/chrubuntu/comments/2hhb31/chrubuntu_on_acer_chromebook_13/) can help you. I haven't used it myself.

**Comment by lovedheart** [comment]
I mean how is L4T installed? not chrubuntu?
